name: dotnet package
permissions: write-all
on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '2.1.x', '3.1.x', '6.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        run: |
            echo $dotnet-version
          
      - name: Install dependencies
        run: |
            dotnet add package System.Security.Cryptography.ProtectedData
            dotnet add package ini-parser
            
      - name: Display dotnet version
        run: dotnet --version
        
      - name: Dotnet publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true /p:PublishTrimmed=true /p:TrimMode=Link
      
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            bin/Release/$dotnet-version/win-x64/publish/MobaXtermDecryptor.exe